services:
  db:
    image: postgres:15.3-alpine
    container_name: chat-app-db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
    ports:
      - 5433:5432


  chat-app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: chat-app-back
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  pgdata:
  chat-app-pgadmin:
